import { StyleSheet, Dimensions } from 'react-native';
import { colors, radius, spacing } from '../theme';

const { width } = Dimensions.get('window');
const imageSize = Math.min(width * 0.7, 280);

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl * 2,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bg,
    padding: spacing.lg,
  },
  errorCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    maxWidth: 360,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  errorIcon: {
    fontSize: 40,
    marginBottom: spacing.md,
  },
  errorTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.text,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  muted: {
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.lg,
  },
  loadingText: {
    color: colors.text,
    fontWeight: '500',
    marginTop: spacing.md,
  },
  textColumn: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  brand: {
    fontSize: 42,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: -0.5,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.primary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.lg,
  },
  infoWrap: {
    maxWidth: 420,
    marginBottom: spacing.lg,
  },
  infoText: {
    fontSize: 15,
    lineHeight: 24,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  infoHighlight: {
    color: colors.primary,
    fontWeight: '600',
    fontSize: 16,
    marginBottom: 0,
  },
  cta: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 32,
    alignItems: 'center',
    alignSelf: 'center',
    minWidth: 220,
    shadowColor: '#2c3e50',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  ctaText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 17,
  },
  carousel: {
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  birdCard: {
    borderRadius: radius.xl,
    paddingTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingBottom: 40,
    alignItems: 'center',
    shadowColor: '#2c3e50',
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
    overflow: 'hidden',
  },
  birdImageWrap: {
    width: imageSize,
    height: imageSize,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  birdImage: {
    width: imageSize,
    height: imageSize,
  },
  imageFallback: {
    color: colors.textMuted,
    fontWeight: '600',
  },
  birdInfo: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
  },
  birdName: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 4,
  },
  scientific: {
    fontSize: 15,
    fontStyle: 'italic',
    color: colors.primary,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  desc: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.textMuted,
    textAlign: 'center',
    maxWidth: 360,
  },
  arrowPrev: {
    position: 'absolute',
    left: 4,
    top: '38%',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(44, 62, 80, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  arrowNext: {
    position: 'absolute',
    right: 4,
    top: '38%',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(44, 62, 80, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  arrowText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 26,
  },
  dots: {
    position: 'absolute',
    bottom: 12,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(44, 62, 80, 0.25)',
  },
  dotActive: {
    backgroundColor: colors.primary,
    width: 22,
    borderRadius: 4,
  },
  learnMoreWrap: {
    marginTop: spacing.xl,
    alignItems: 'center',
  },
  learnMore: {
    borderWidth: 2,
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: 'transparent',
  },
  learnMoreText: {
    fontWeight: '600',
    fontSize: 15,
  },
  retry: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 28,
  },
  retryText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
});
